### ISSUE TITLE
Exception Handler

### ISSUE THREAD

**Issue by bliutech** [pbrucla/SecureOS#11]
Needs some help with debugging. Exception that prints stuff out for debugging.

**Comment by danieltherealyang** [comment]
Create a generic exception handler interface. Make it so that typical OOP inheritance-like design patterns can be used to easily create new exception types and attach handler function to the interface.
This is C so probably want to do something with function pointers idk.

**Comment by bliutech** [comment]
Since we only need one process, no exception handlers needed for this quarter.
